### ISSUE TITLE
Schedule a run doesn't work with string

### ISSUE THREAD

**Issue by meytal127** [Zooz/predator#454]
**Describe the bug**
Trying to create a schedule run with the cron expression '0 20 0 7 OCT ? 2020' returns an error.
Pop up in the ui:
```
Error: Request failed with status code 500
Description: Internal server error
More info:
```

In the console:
```
500 (Internal Server Error)
```

**To Reproduce**
1. Go to 'Run test'
2. Set all the test relevant parameters
3. Set this as Cron expersion: '0 20 0 7 OCT ? 2020'
4. Click on 'Schedule'
5. See error

**Expected behavior**
Schedule a run without any errors

**Screenshots**
![image](https://user-images.githubusercontent.com/16078045/95212270-2f30ab00-07f6-11eb-828f-8b722addd09f.png)

**Version:**
 - Predator: 1.5.4
 - Database mysql

**Additional context**
eventually the schedule was created.

**Comment by enudler** [comment]
I did some triage to this bug and it seems that our backend uses:
https://www.npmjs.com/package/cron
this package doesn't support month like OCT but rather as '9' (0-11)

Two things need to be done here
1. add validation on swagger on cron regex according to the above package or catch the exception from jobManager and return 400 (high priority)
2. Block special chars like strings in this field in the ui form (lower priority)

**Comment by Hayden-Yu** [comment]
Hi, I found my way here from hacktoberfest. May I work on this issue?

**Comment by enudler** [comment]
Hi @Hayden-Yu 
Sure, i will assign that to you. 
We are available in slack for any questions.

**Comment by Hayden-Yu** [comment]
@enudler Thank you!

I took a closer look into the cron package and found that [it actually does support month aliases like "OCT"](https://github.com/kelektiv/node-cron/blob/master/lib/time.js#L391). It is the "?" in the screenshot that's causing the problem but the direction you gave is on point.

I plan to add an additional validation in [jobVerifier.verifyJobBody](https://github.com/Zooz/predator/blob/master/src/jobs/helpers/jobVerifier.js#L4) using the CronTime parser from cron package.

Please let me know if you would suggest otherwise.
