### ISSUE TITLE
Predator UI crashes when test is corrupted

### ISSUE THREAD

**Issue by enudler** [Zooz/predator#498]
**Describe the bug**
When a test edited through API and becomes with an invalid format that UI can't render, Predator crashes
**To Reproduce**

`curl -X POST \
  http://predator.eks-mars-apps.zooz.co/v1/tests/ \
  -H 'Content-Type: application/json;charset=UTF-8' \
  -d '{
    "name": "Corpuuted Test",
    "description": "Corpuuted Test",
    "type": "basic",
    "config": {
        "target": "",
        "plugins": {
            "expect": {}
        }
    },
    "artillery_test": {
    	"scenarios": [],
        "before": {
            "flow": [
                {
                    "post": {
                        "url": "http://predator.dev",
                        "capture": {
                            "json": "$.should_be_array",
                            "as": "crash"
                        },
                        "expect": []
                    }
                }
            ]
        }
    }
}'`

**Expected behavior**
Predator UI should not crash, and the error popup should jump with "Oh no, I can't render this test, please use the API"

**Version:**
 - Predator:1.5.4

**Comment by anusha5695** [comment]
@enudler I can pick this

**Comment by enudler** [comment]
thanks @anusha5695 
assigned

**Comment by anusha5695** [comment]
Hey @enudler , have some questions. I see that to render a test you would need
name, description, id, config target, before, atleast one scenario, type, processor id, csv_file_id

From the code to render the test in edit mode, it appears that crash can occur only if
- config is not present 
- scenario is not present
- scenario not being array type
- config not being object type
- before not being array type
- scenario.flow not being array type
- scenario.flow.every subitem not being object type
- captures not being array type
- each item inside capture not being object type
- expect not being array type
- each item inside expect not being object type

Out of these I see fee are restricted at swagger. 

1.I think first all these should be restricted at a swagger level because an API shouldn't consume incorrect format. 
2.We can also proactively add checks for all these in UI and show error popup.

Do you think we should not do just 2) but instead do both 1 and 2

**Comment by enudler** [comment]
hi @anusha5695 
I would say that for now, we need to catch this error in the UI and show some popup instead of crashing the UI
2nd priority is to add this to our open API spec

**Comment by anusha5695** [comment]
@enudler : Okay sure.
